# ####################################################################

#  Created by Genus(TM) Synthesis Solution 23.16-s067_1 on Thu Apr 02 20:02:42 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design chip_top

create_clock -name "mclk" -period 5.4 -waveform {0.0 2.7} [get_ports clock]
create_clock -name "vclk" -period 5.4 -waveform {0.0 2.7} 
set_load -pin_load 0.008 [get_ports {MemWriteBus[63]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[62]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[61]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[60]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[59]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[58]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[57]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[56]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[55]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[54]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[53]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[52]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[51]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[50]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[49]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[48]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[47]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[46]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[45]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[44]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[43]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[42]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[41]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[40]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[39]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[38]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[37]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[36]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[35]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[34]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[33]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[32]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[31]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[30]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[29]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[28]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[27]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[26]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[25]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[24]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[23]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[22]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[21]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[20]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[19]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[18]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[17]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[16]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[15]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[14]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[13]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[12]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[11]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[10]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[9]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[8]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[7]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[6]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[5]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[4]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[3]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[2]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[1]}]
set_load -pin_load 0.008 [get_ports {MemWriteBus[0]}]
set_load -pin_load 0.008 [get_ports MemWriteValid]
set_load -pin_load 0.008 [get_ports power_ack]
set_load -pin_load 0.008 [get_ports MemOverflow]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[31]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[30]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[29]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[28]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[27]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[26]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[25]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[24]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[23]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[22]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[21]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[20]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[19]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[18]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[17]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[16]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[15]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[14]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[13]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[12]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[11]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[10]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[9]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[8]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[7]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[6]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[5]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[4]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[3]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[2]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[1]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemReadBus[0]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports reset]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {cs[1]}]
set_input_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {cs[0]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[63]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[62]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[61]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[60]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[59]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[58]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[57]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[56]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[55]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[54]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[53]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[52]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[51]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[50]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[49]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[48]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[47]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[46]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[45]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[44]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[43]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[42]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[41]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[40]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[39]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[38]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[37]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[36]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[35]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[34]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[33]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[32]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[31]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[30]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[29]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[28]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[27]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[26]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[25]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[24]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[23]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[22]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[21]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[20]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[19]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[18]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[17]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[16]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[15]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[14]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[13]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[12]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[11]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[10]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[9]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[8]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[7]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[6]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[5]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[4]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[3]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[2]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[1]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports {MemWriteBus[0]}]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports MemWriteValid]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports power_ack]
set_output_delay -clock [get_clocks vclk] -add_delay 0.6 [get_ports MemOverflow]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[31]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[30]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[29]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[28]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[27]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[26]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[25]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[24]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[23]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[22]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[21]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[20]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[19]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[18]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[17]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[16]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[15]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[14]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[13]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[12]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[11]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[10]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[9]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[8]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[7]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[6]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[5]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[4]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[3]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[2]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[1]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {MemReadBus[0]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports clock]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports reset]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {cs[1]}]
set_driving_cell -lib_cell BUFX12 -library slow_vdd1v0 -pin "Y" [get_ports {cs[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.1 [get_clocks mclk]
set_clock_uncertainty -hold 0.1 [get_clocks mclk]
set_clock_uncertainty -setup 0.1 [get_clocks vclk]
set_clock_uncertainty -hold 0.1 [get_clocks vclk]
